apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ai-registry.server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-registry.server.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.server.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "ai-registry.server.selectorLabels" . | nindent 6 }}
