apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-registry.web.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-registry.web.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  AUTH_SECRET: {{ .Values.web.authSecret | quote }}
  AUTH_KEYCLOAK_ID: {{ .Values.web.keycloakId | quote }}
  AUTH_KEYCLOAK_SECRET: {{ .Values.web.keycloakSecret | quote }}
