apiVersion: v2
name: ai-registry
description: A centralized registry for MCP servers
type: application
version: 0.4.1
appVersion: "0.4.1"
keywords:
  - ai
  - mcp
  - registry
home: https://github.com/haibread/ai-registry
sources:
  - https://github.com/haibread/ai-registry
maintainers:
  - name: Haibread
