{{- $v := include "ai-registry.api.values" . | fromYaml -}}
{{- if $v.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ai-registry.api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-registry.api.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ai-registry.api.fullname" . }}
  minReplicas: {{ $v.autoscaling.minReplicas }}
  maxReplicas: {{ $v.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $v.autoscaling.targetCPUUtilizationPercentage }}
    {{- if $v.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $v.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
